version: '3'
services:
  db:
    image: postgres:9.6
    volumes:
      - /docker/factorio/psql:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5433:5432"
  web:
    image: ponkotuy/factoriorecipe
    env_file: .env_web
    ports:
      - "9048:9000"
    depends_on:
      - db
